

// Assignment 1 Problem 1
// Partner Patrick Burden
// partner1username pburden
// Partner Name2 Seydi Sy
// partner2username Seydi
// 2 April 2012


import java.util.*;

/** Class to count frequencies of the words generated by an
 *   iterator. */
public class WordCounter{
    int wordCount;
    ArrayList<Word> list;
    Comparator<Word> f;
    
    public WordCounter(){ 
    	this.wordCount = 0;
    	this.list = new ArrayList<Word>();
    }
  
    /** record the words generated by the given iterator*/
    // Record the Word objects generated by the given Iterator
    //   and update the number of ocurrences
    public void countWords(Iterator<Word> it){
        while(it.hasNext()){
        	Word temp = it.next();
        	if(list.contains(temp)){
        	it.next().increment();
        	}else{
        		wordCount = wordCount +1;
        	}
        }
    }
  
    /** Count the number of different words in this Counter */
    // How many different Words has this WordCounter recorded?
    public int words(){
        return wordCount;
    }  
  
    /** Print the words and their frequencies for the top n words */
    // Prints the n most common words and their frequencies.
    public void printWords(int n){
    	ArrayList<Word> temp = list;
    	
    	if(n < temp.size()){
    		for(int index = 0; index < n; index = index + 1){
    			for(int x = 0; 0 < temp.size(); x = x +1){
    				if(mostFreq(temp.get(x)))
    	    			System.out.println(temp.get(index).toString());
    				}
    			}

    		}else{
    		for(int index = 0; index < temp.size(); index = index + 1){
    			System.out.println(temp.get(index).toString());
    		}
    	}
    }
    //finds the one with the highest freq
    public boolean mostFreq(Word w){
    	int check = 0;
    	for(int index = 0; index < list.size(); index = index + 1)
    		if(w.f.compare(w, list.get(index)) < 0){
    			check = 1;
    			break;
    		}
    	return (check == 0);
    }
}
